path_prefix: /var/apps

static:
  vindsiden-backend:
    - config.js
    - models
    - package.json
    - routes
    - server.js

environments:
  production: &production
    hosts: [s3c1.muda.no]
    user:  www-data
  default:
    <<: *production

hooks:
  remote:
    after:
      - cd /var/apps/vindsiden-backend;npm install
      - sudo /usr/sbin/service vindsiden-backend restart
